#!/bin/sh

set -eux

ulimit -c unlimited  # allow a core file to be written

mkdir -p build bin
rm -f build/core  # remove previous core file if any

cd build
# rm CMakeCache.txt  # invalidate options (sigh

cmake -DCMAKE_BUILD_TYPE=Release ..
make VERBOSE=1

cd ..
cp build/cli/cli bin/
strip bin/cli
